#
# Module manifest for module 'GetClrCallStack'
#
# Generated by: Patrick Meinecke
#
# Generated on: 6/16/2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'GetClrCallStack.dll'

# Version number of this module.
ModuleVersion = '1.0.0'

# ID used to uniquely identify this module
GUID = '98444ca0-3fdf-4a68-bf68-fe51efa4e608'

# Author of this module
Author = 'Patrick Meinecke'

# Company or vendor of this module
CompanyName = 'Community'

# Copyright statement for this module
Copyright = '(c) Patrick Meinecke. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Get the managed (C#) call stack for every thread in a target process.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'GetClrCallStack.format.ps1xml'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'Get-ClrCallStack'

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/SeeminglyScience/GetClrCallStack/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/SeeminglyScience/GetClrCallStack'

        # ReleaseNotes of this module
        ReleaseNotes = 'Initial Release'
    } # End of PSData hashtable

} # End of PrivateData hashtable

}
